pokedex = {
    "001": {
        "nome": "Bulbasaur",
        "tipo": ["Grama", "Venenoso"],
        "altura": 0.7,
        "peso": 6.9,
        "categoria": "Semente",
        "habilidade": "Overgrow",
        "hp": 45,
        "ataque": 49,
        "defesa": 49,
        "ataque_especial": 65,
        "defesa_especial": 65,
        "velocidade": 45
    },
    "004": {
        "nome": "Charmander",
        "tipo": ["Fogo"],
        "altura": 0.6,
        "peso": 8.5,
        "categoria": "Lagarto",
        "habilidade": "Blaze",
        "hp": 39,
        "ataque": 52,
        "defesa": 43,
        "ataque_especial": 60,
        "defesa_especial": 50,
        "velocidade": 65
    },
    "007": {
        "nome": "Squirtle",
        "tipo": ["Água"],
        "altura": 0.5,
        "peso": 9.0,
        "categoria": "Tartaruga",
        "habilidade": "Torrent",
        "hp": 44,
        "ataque": 48,
        "defesa": 65,
        "ataque_especial": 50,
        "defesa_especial": 64,
        "velocidade": 43
    },
    "025": {
        "nome": "Pikachu",
        "tipo": ["Elétrico"],
        "altura": 0.4,
        "peso": 6.0,
        "categoria": "Rato",
        "habilidade": "Static",
        "hp": 35,
        "ataque": 55,
        "defesa": 40,
        "ataque_especial": 50,
        "defesa_especial": 50,
        "velocidade": 90
    },
    "039": {
        "nome": "Jigglypuff",
        "tipo": ["Normal", "Fada"],
        "altura": 0.5,
        "peso": 5.5,
        "categoria": "Balão",
        "habilidade": "Cute Charm",
        "hp": 115,
        "ataque": 45,
        "defesa": 20,
        "ataque_especial": 45,
        "defesa_especial": 25,
        "velocidade": 20
    },
    "052": {
        "nome": "Meowth",
        "tipo": ["Normal"],
        "altura": 0.4,
        "peso": 4.2,
        "categoria": "Gato",
        "habilidade": "Pickup",
        "hp": 40,
        "ataque": 45,
        "defesa": 35,
        "ataque_especial": 40,
        "defesa_especial": 40,
        "velocidade": 90
    },
    "092": {
        "nome": "Gastly",
        "tipo": ["Fantasma", "Venenoso"],
        "altura": 1.3,
        "peso": 0.1,
        "categoria": "Gás",
        "habilidade": "Levitate",
        "hp": 30,
        "ataque": 35,
        "defesa": 30,
        "ataque_especial": 100,
        "defesa_especial": 35,
        "velocidade": 80
    },
    "132": {
        "nome": "Ditto",
        "tipo": ["Normal"],
        "altura": 0.3,
        "peso": 4.0,
        "categoria": "Transformação",
        "habilidade": "Limber",
        "hp": 48,
        "ataque": 48,
        "defesa": 48,
        "ataque_especial": 48,
        "defesa_especial": 48,
        "velocidade": 48
    },
    "133": {
        "nome": "Eevee",
        "tipo": ["Normal"],
        "altura": 0.3,
        "peso": 6.5,
        "categoria": "Evolução",
        "habilidade": "Run Away",
        "hp": 55,
        "ataque": 55,
        "defesa": 50,
        "ataque_especial": 45,
        "defesa_especial": 65,
        "velocidade": 55
    },
    "150": {
        "nome": "Mewtwo",
        "tipo": ["Psíquico"],
        "altura": 2.0,
        "peso": 122.0,
        "categoria": "Genético",
        "habilidade": "Pressure",
        "hp": 106,
        "ataque": 110,
        "defesa": 90,
        "ataque_especial": 154,
        "defesa_especial": 90,
        "velocidade": 130
    }
}

if __name__ == "__main__":

    print(pokedex["001"])